Fix/analyze java build
infonl/dimpact-zaakafhandelcomponent pull request #12
Opened 2023-07-27 14:04 UTC by jasper88

2023-07-27 14:12 UTC, Jorann submitted a review, later dismissed
All checks passed :party-parrot:

2023-07-27 14:18 UTC, Jorann submitted a review, later dismissed

2023-07-27 15:27 UTC, edgarvonk requested changes

2023-07-27 15:27 UTC, edgarvonk commented on .github/workflows/codeql-analysis.yml
> +          distribution: "temurin"
Ik denk nog wel handig om hier de Maven cache aan toe te voegen. Onze Java build is nl een Maven build en dat is wat die CodeQL action ook gebruikt. Dus hier aan toevoegen:

          `cache: maven`
          
    Net als in onze andere GitHub workflow.

2023-07-27 15:27 UTC, edgarvonk commented on .github/workflows/codeql-analysis.yml
> +          java-version: "17"
Ik zou dit hetzelfde doen als in onze andere build workflow:

` java-version: ${{ env.JAVA_VERSION }}
`

en dan bovenin:

`
env:
  JAVA_VERSION: '17'
 `
 
 Maakt het net ietsje makkelijker om direct te zien welke Java versie we gebruiken. Detail hoor.

2023-07-27 15:30 UTC, bas-info-nl approved these changes

2023-07-28 07:41 UTC, jasper88 commented on .github/workflows/codeql-analysis.yml
> +    branches: [main]
Ah goeie, mijn editor heeft dit format aangepast. De eslint package die ik in de andere branch heb toegevoegd pakt (denk ik) de files aan binnen de frontend app.

2023-07-31 07:06 UTC, edgarvonk approved these changes

2023-07-31 09:11 UTC, merged