fix: change urls to new urls and refactor urls to work with env vars
infonl/dimpact-zaakafhandelcomponent pull request #144
Opened 2023-10-24 12:15 UTC by RickWoltheus

Location api's used an url that has moved to a new endpoint. Als refactored the implementations of the url so it's easier to change in the future

Solves PZ-525

2023-10-24 12:29 UTC, edgarvonk requested changes

2023-10-24 12:29 UTC, edgarvonk commented on src/main/app/src/app/bag/bag-locatie/bag-locatie.component.ts
> +      url: environment.ACHTERGRONDKAART_API_URL,
Maybe consider translating this to English? `BACKGROUND_MAP_API_URL` or something?

2023-10-24 12:29 UTC, edgarvonk commented on src/main/app/src/app/shared/location/location.service.ts
> + * SPDX-FileCopyrightText: 2022 Lifely
Dit mag niet licentie-technisch gezien. Je mag niet zomaar een licentie header aanpassen van bestaande code. Je moet altijd de originele partij blijven noemen. Zie: https://github.com/infonl/dimpact-zaakafhandelcomponent/blob/main/CONTRIBUTING.md

2023-10-25 09:12 UTC, edgarvonk commented on src/main/app/src/app/shared/location/location.service.ts
> + * SPDX-FileCopyrightText: 2022 Lifely
Wat je dus moet doen volgens onze licentie is de licentie header veranderen naar:

```
/*
 * SPDX-FileCopyrightText: 2022 Atos, 2023 Lifely
 * SPDX-License-Identifier: EUPL-1.2+
 */
 ```

2023-10-25 09:27 UTC, bas-info-nl approved these changes

2023-10-25 13:37 UTC, Jorann approved these changes
Good

2023-10-25 14:05 UTC, edgarvonk approved these changes

2023-10-25 14:12 UTC, merged