feature: list only Zaak UUIDs for reindexing
infonl/dimpact-zaakafhandelcomponent pull request #1708
Opened 2024-09-10 14:21 UTC by hsiliev

Ignore exceptions during object conversion

Solves: PZ-3493

2024-09-10 15:07 UTC, edgarvonk requested changes

2024-09-10 20:24 UTC, hsiliev commented on src/main/java/net/atos/client/zgw/zrc/model/ZaakUuid.java
> +public record ZaakUuid(UUID uuid) {
Using just UUID is probably possible, but requires a custom deserializer as far as I can tell. Don't think it is worth the effort.

Instead we use the fact that this object can use the listZaken payload but use deserialization only for UUID

2024-09-10 20:38 UTC, hsiliev commented on src/main/kotlin/net/atos/zac/zoeken/IndexingService.kt
> +            objectIds.map { continueOnExceptions(objectType) { getConverter(objectType).convert(it) } },
We use map to loop over all IDs and load all the objects.
Refactored this part a bit to make this more obvious.

2024-09-10 20:58 UTC, hsiliev commented on src/main/kotlin/net/atos/zac/zoeken/IndexingService.kt
>      private fun reindexZakenPage(pageNumber: Int, totalSize: Int) {
Changed to totalCount

2024-09-11 07:49 UTC, edgarvonk commented on src/main/kotlin/net/atos/zac/zoeken/IndexingService.kt
> +            objectIds.map { continueOnExceptions(objectType) { getConverter(objectType).convert(it) } },
clear!

2024-09-11 07:49 UTC, edgarvonk approved these changes
very nice

2024-09-11 07:51 UTC, merged