fix: return error codes
infonl/dimpact-zaakafhandelcomponent pull request #2233
Opened 2024-12-11 15:13 UTC by xiduzo

Return error codes, instead of static text, to the frontend and have the frontend do the translations accordingly

Solves PZ-4584

2024-12-11 15:19 UTC, infonl-marcel approved these changes
Great to move into this solution direction! 👍🏽

2024-12-12 11:44 UTC, edgarvonk requested changes

2024-12-12 11:44 UTC, edgarvonk commented on src/main/app/src/assets/i18n/en.json
> +  "msg.error.case.has.open.subcases": "This case has open subcases and can not be closed",
```suggestion
  "msg.error.case.has.open.subcases": "This case has open subcases and cannot be closed",
```

https://www.merriam-webster.com/grammar/cannot-vs-can-not-is-there-a-difference ;-)

2024-12-12 11:44 UTC, edgarvonk commented on src/main/app/src/assets/i18n/en.json
> +  "msg.error.case.has.locked.information.objects": "this case has locked information objects and can not be closed",
```suggestion
  "msg.error.case.has.locked.information.objects": "This case has locked documents and cannot be closed",
```

As far as I know we don't use the term 'information objects' in the UI.

2024-12-12 14:22 UTC, edgarvonk commented on src/main/app/src/assets/i18n/en.json
> +  "msg.error.case.has.open.subcases": "This case has open subcases and can not be closed",
And: close the sentence with a `.` or not?

2024-12-12 15:21 UTC, edgarvonk requested changes

2024-12-13 15:15 UTC, bas-info-nl approved these changes

2024-12-13 15:15 UTC, bas-info-nl commented on src/main/app/src/assets/i18n/nl.json
> +  "msg.error.case.has.open.subcases": "Deze hoofdzaak heeft open deelzaken en kan niet afgesloten worden",
None of the messages have a `.` at the end. Those are added when building the onscreen message I believe, can you confirm @xiduzo ?

2024-12-16 07:55 UTC, xiduzo commented on src/main/app/src/assets/i18n/nl.json
> +  "msg.error.case.has.open.subcases": "Deze hoofdzaak heeft open deelzaken en kan niet afgesloten worden",
I do not see anything for this in the code-base. But to keep them consitent I would either add an `.` to all of the errors or tot none.

2024-12-16 08:21 UTC, edgarvonk commented on src/main/app/src/assets/i18n/nl.json
> +  "msg.error.case.has.open.subcases": "Deze hoofdzaak heeft open deelzaken en kan niet afgesloten worden",
>None of the messages have a . at the end. 

That's not true! Most of the errors message do (scroll up). Better to be consistent here I feel.

2024-12-16 09:54 UTC, edgarvonk approved these changes

2024-12-16 10:39 UTC, merged