Feature/pz 1081 local office converter
infonl/dimpact-zaakafhandelcomponent pull request #453
Opened 2024-01-22 14:12 UTC by Jorann

This will add and enable office converter locally. There is an issue still with auto-reload tha tI was not able to fix. It does work on the test environment.

PZ-1081

2024-01-22 14:27 UTC, edgarvonk requested changes

2024-01-22 14:27 UTC, edgarvonk commented on docker-compose.yaml
> +  office-converter:
Goed om ook even toe te voegen aan het lijstje services in de `installDockerCompose.md`.

2024-01-22 14:27 UTC, edgarvonk commented on docker-compose.yaml
> +      - "9999:8080"
Maakt niet zo heel veel uit maar ik zou liever in de 8xxx range blijven voor alle '8080' gemapte poorten zeg maar zoals we ook doen voor de andere Docker containers. 8083 of zo iets?

2024-01-22 14:27 UTC, edgarvonk commented on docker-compose.yaml
Ik mis een change hier voor de ZAC container?

Daar hebben we nu: `OFFICE_CONVERTER_CLIENT_MP_REST_URL=http://localhost:9999 # dummy for now`. Die moet nu gezet worden lijkt me?

2024-01-23 10:31 UTC, Jorann commented on docker-compose.yaml
> +      - "9999:8080"
Zoals besproken: heel lastig, omdat we dan een docx zouden moeten multipart posten op de endpoint. Hiermee test je dan ook de externe dienst ipv ZAC.

2024-01-23 11:24 UTC, edgarvonk commented on docker-compose.yaml
> +      - "9999:8080"
Het zou uiteindelijk wel fijn zijn om het bewuste `convert` endpoint in de `InformatieObjectenRESTService` van ZAC te testen met een integratietest. Die geeft op dit moment een 500 terug (want nu geen office converter geconfigureerd). Maar inderdaad, daarvoor moet je wel eerst een document uploaden in ZAC. Niet triviaal maar an sich best wel te doen met een integratietest lijkt me hoor. Dan testen we ook direct het 'document toevoegen' endpoint. 

Je zou dan indirect inderdaad ook die office converter service testen maar dat is prima. Je test met name de code in ZAC die dit allemaal verzorgd en je test ook direct onze Docker Compose opzet wat ook fijn is. Voor een volgende sprint wellicht.

2024-01-23 11:27 UTC, edgarvonk requested changes

2024-01-23 11:27 UTC, edgarvonk commented on docker-compose.yaml
> +      - OFFICE_CONVERTER_CLIENT_MP_REST_URL=http://localhost:8083
`localhost` gaat niet werken want als je ZAC in Docker draait dan kan ie niet bij localhost. Zo werkt Docker.

Maar dat is ook niet nodig. Dit is puur een 'interne' service binnen het Docker Compose netwerk dus volgens mij kan je hier gewoon `http://office-converter:8080` doen zoals we bij de andere variabelen ook doen?

2024-01-23 12:45 UTC, Jorann commented on docker-compose.yaml
> +      - "9999:8080"
https://dimpact.atlassian.net/browse/PZ-1234

2024-01-23 15:55 UTC, edgarvonk approved these changes

2024-01-23 15:55 UTC, merged