Chore/add eslint
infonl/dimpact-zaakafhandelcomponent pull request #6
Opened 2023-07-25 14:34 UTC by jasper88

- remove outdated tslint
- add eslint
- add prettier

2023-07-25 15:19 UTC, edgarvonk reviewed
I suggest to wait with merging this PR until we have at least a very basic GitHub workflow where we actually build the software. :-)

2023-07-26 05:43 UTC, bas-info-nl approved these changes

2023-07-26 07:37 UTC, Jorann approved these changes

2023-07-26 08:55 UTC, edgarvonk requested changes
Hoe mooi en nuttig deze PR ook is, ik stel voor dat we hem niet mergen totdat we een besluit hebben genomen over de laatste code wijzigingen van de upstream Atos repo aangezien onze fork nu achterloopt. Deze PR nu al te mergen levert denk ik net te veel risico op. Ook kunnen we nog wel even wachten hiermee.

2023-08-07 06:39 UTC, edgarvonk reviewed
Is it clear to future (frontend) developers how this works? Or does it make sense to add a few lines of documentation about this in the readme?

2023-08-24 11:53 UTC, edgarvonk approved these changes

2023-08-24 11:59 UTC, merged