feat: add code style settings doc for IntelliJ Idea
infonl/dimpact-zaakafhandelcomponent pull request #641
Opened 2024-02-27 12:00 UTC by hsiliev

2024-02-27 12:15 UTC, edgarvonk requested changes
Nice! We do also have IntelliJ docs already in our `INSTALL.md` (`### Run ZAC in IntelliJ`) and link from INSTALL.md to ths file. 

I think it makes sense to move those to this new file as well. I'm a little reluctant however with all this IntelliJ documentation because we are an open source project and I think it is a little strange to sort of 'push' a specific IDE but oh well. It does make our life easier so it's fine.

Also so far we have added a link to all development docs in our `README.md` because that is the index/starting page if you use GitHub. I think good to add a link there to this new file.

2024-02-27 12:32 UTC, edgarvonk commented on docs/development/intellij.md
> +4. Open `./config/Dimpact.xml` from the project root
Oh, yes I would not name this `Dimpact.xml`. This open source project should really stand on it's own and be independent of 'Dimpact' I would rename this just `zac.xml`.

2024-02-27 13:25 UTC, bas-info-nl approved these changes

2024-02-27 19:35 UTC, hsiliev commented
> Nice! We do also have IntelliJ docs already in our `INSTALL.md` (`### Run ZAC in IntelliJ`). I think it makes sense to move those to this new file as well and link from INSTALL.md to this file.
> 
> I'm a little reluctant however with all this IntelliJ documentation because we are an open source project and I think it is a little strange to sort of 'push' a specific IDE but oh well. It does make our life easier so it's fine.
> 
> Also so far we have added a link to all development docs in our `README.md` because that is the index/starting page if you use GitHub. I think good to add a link there to this new file.

Merged/Extracted IDE specific stuff in a new file

2024-02-28 08:16 UTC, edgarvonk approved these changes
very nice :-)

2024-02-28 08:30 UTC, merged